#!/bin/bash
printf "%s\n" "$(printf "%0s\n" "$(( $(echo $WATER | tr water 01234) + $(echo $STIR | tr stir. 01234) ))" | awk '{gsub(/0/,"b"); gsub(/1/,"e"); gsub(/2/,"s"); gsub(/3/,"t"); gsub(/4/,"c"); gsub(/5/,"h"); gsub(/6/,"o"); gsub(/7/,"l"); print}' | rev)"
